export declare const DEBUG: boolean;
export declare const WIDTH = 160;
export declare const HEIGHT = 160;
export declare const STORAGE_SIZE = 1024;
export declare const CRASH_TITLE = "WASM-4";
export declare const COLORS: number[];
export declare const ADDR_PALETTE = 4;
export declare const ADDR_DRAW_COLORS = 20;
export declare const ADDR_GAMEPAD1 = 22;
export declare const ADDR_GAMEPAD2 = 23;
export declare const ADDR_GAMEPAD3 = 24;
export declare const ADDR_GAMEPAD4 = 25;
export declare const ADDR_MOUSE_X = 26;
export declare const ADDR_MOUSE_Y = 28;
export declare const ADDR_MOUSE_BUTTONS = 30;
export declare const ADDR_SYSTEM_FLAGS = 31;
export declare const ADDR_FRAMEBUFFER = 160;
export declare const BUTTON_X = 1;
export declare const BUTTON_Z = 2;
export declare const BUTTON_LEFT = 16;
export declare const BUTTON_RIGHT = 32;
export declare const BUTTON_UP = 64;
export declare const BUTTON_DOWN = 128;
export declare const MOUSE_LEFT = 1;
export declare const MOUSE_RIGHT = 2;
export declare const MOUSE_MIDDLE = 4;
export declare const SYSTEM_PRESERVE_FRAMEBUFFER = 1;
export declare const SYSTEM_HIDE_GAMEPAD_OVERLAY = 2;
export declare const PAUSE_UNFOCUSED = 1;
export declare const PAUSE_CRASHED = 2;
export declare const PAUSE_REBOOTING = 4;
export declare const FONT: Uint8Array;
export declare const showDevToolsQueryKey = "devtools-open";
