[package]
name = "xtask-build"
version = "0.1.0"
edition = "2021"

[dependencies]
cargo_metadata = "0.14.1"
binary-install = "0.0.3-alpha.1"
env_logger = { version = "0.9.0", default-features = false }
log = "0.4"
