require "wasm4"

local smiley: []uint8 = {
  0b11000011,
  0b10000001,
  0b00100100,
  0b00100100,
  0b00000000,
  0b00100100,
  0b10011001,
  0b11000011,
};

local function update(): void
  $DRAW_COLORS = 2
  text("Hello from Nelua!", 10, 10)

  local gamepad = $GAMEPAD1
  if gamepad & BUTTON_1 ~= 0 then
    $DRAW_COLORS = 4
  end

  blit(&smiley, 76, 76, 8, 8, BLIT_1BPP)
  text("Press X! to blink", 16, 90)
end

## setup_wasm4_callbacks(update)
