[alias]
xtask = "run --package xtask --"

[env]
# Log levels available: "error", "warn", "info", "debug", "trace"
CARGO_XTASK_LOG = "info"
# Uncomment this to forbid wasm-opt installation and skip the prompt
# WASM_OPT_NOINSTALL = "1"
WASM_OPT_INSTALL_VERSION = "version_105"

[target.wasm32-unknown-unknown]
rustflags = [
    # Import memory from WASM-4
    "-C", "link-arg=--import-memory",
    "-C", "link-arg=--initial-memory=65536",
    "-C", "link-arg=--max-memory=65536",

    # Temporary workaround for #255 issue.
    # Reserve 8192 bytes of Rust stack space, offset from 6560.
    # Bump this value, 16-byte aligned, if the framebuffer gets corrupted.
    "-C", "link-arg=-zstack-size=14752",
]
