#!/usr/bin/env node

const memory = {
    _PAD_START: 4,

    PALETTE: 4*4,
    DRAW_COLORS: 2,
    // CLIP_X: 1,
    // CLIP_Y: 1,
    // CLIP_WIDTH: 1,
    // CLIP_HEIGHT: 1,

    GAMEPAD1: 1,
    GAMEPAD2: 1,
    GAMEPAD3: 1,
    GAMEPAD4: 1,
    MOUSE_X: 2,
    MOUSE_Y: 2,
    MOUSE_BUTTONS: 1,

    SYSTEM_FLAGS: 1,

    TIME: 8,

    _RESERVED: 120,

    // Framebuffer should be 64 bit aligned
    FRAMEBUFFER: 160*160 >> 2,
};

const cTypes = {
    PALETTE: "uint32_t",
    DRAW_COLORS: "uint16_t",
    MOUSE_X: "const int16_t",
    MOUSE_Y: "const int16_t",
    SYSTEM_FLAGS: "uint8_t",
    TIME: "uint64_t",
    FRAMEBUFFER: "uint8_t",
};

const rustTypes = {
    // TODO(2021-08-10)
};

const goTypes = {
    PALETTE: "[4]uint32",
    DRAW_COLORS: "uint16",
    MOUSE_X: "int16",
    MOUSE_Y: "int16",
    FRAMEBUFFER: "[6400]uint8",
};

const neluaTypes = {
    PALETTE: "uint32",
    DRAW_COLORS: "uint16",
    MOUSE_X: "int16",
    MOUSE_Y: "int16",
    SYSTEM_FLAGS: "uint8",
    TIME: "uint64",
    FRAMEBUFFER: "uint8",
};

function generate (fn) {
    let p = 0;
    for (let name in memory) {
        if (!name.startsWith("_")) {
            const addr = `0x${p.toString(16).padStart(2, "0")}`;
            console.log(fn(name, addr));
        }
        p += memory[name];
    }
    console.log();
}

console.log("// Runtime constants.js");
generate((name, addr) => `export const ADDR_${name} = ${addr};`);

console.log("// C");
generate((name, addr) => `#define ${name} ((${cTypes[name] || "const uint8_t"}*)${addr})`);

// TODO D

console.log("// AssemblyScript");
generate((name, addr) => `export const ${name}: usize = ${addr};`);

console.log("// Rust");
generate((name, addr) => `pub const ${name}: *const u8 = ${addr} as *const u8;`);

console.log("// Go");
generate((name, addr) => `var ${name} = (*${goTypes[name] || "uint8"})(unsafe.Pointer(uintptr(${addr})));`);

console.log("// Nelua");
generate((name, addr) => `global ${name} <const> = (@*${neluaTypes[name] || "uint8"})(${addr})`);

var sum = 0;
for (let name in memory) {
    sum += memory[name];
}
console.log("--global-base="+sum);
