#!/bin/sh -e

runtime=$PWD/runtimes/web
site=$PWD/site
cli=$PWD/cli

# Build runtime
cd "$runtime"
npm ci
npm run build

# Build and deploy site
cd "$site"
rm -rf static/embed
cp -r "$runtime/dist" static/embed
npm ci
npm run build
