#!/bin/sh -e

repo-root=$PWD
runtime=$PWD/runtimes/web
devtools=$PWD/devtools/web
site=$PWD/site
cli=$PWD/cli

npm ci
# Build runtime
npm -w wasm4-runtime run build

# Build and deploy site
rm -rf "$site/static/embed"
cp -r "$runtime/dist" "$site/static/embed"
npm -w site run build

