#!/bin/sh -e

runtime=$PWD/runtimes/web
devtools=$PWD/devtools/web
site=$PWD/site
cli=$PWD/cli

# Build runtime
cd "$devtools"
npm ci
cd "$runtime"
npm ci
npm run build

# Build and deploy site
cd "$site"
rm -rf static/embed
cp -r "$runtime/dist/slim" static/embed
npm ci
npm run build
