#!/bin/env sh
set -e

## A WASM-4 project should look like this:
##    +- Folder -+
##    | app.d    |
##    | build    |
##    +----------+

output="cart.wasm"
source="source"
 files="source/app.d"
 flags=""

cd "$(dirname "$0")"
ldc2 -of=$output \
    $files $flags -I=$source \
    -i -betterC \
    --mtriple=wasm32 \
    --checkaction=halt \
    --d-version=JokaSmallFootprint \
    --d-version=JokaMathStubs \
    -L--export=update \
    -L--strip-all \
    -L--no-entry \
    -L--stack-first \
    -L--import-memory \
    -L--initial-memory=65536 \
    -L--max-memory=65536 \
    -L-zstack-size=14752
